stages:
  clean_data:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
      - data/raw/Raw_Data.csv
    outs:
      - data/processed/cleaned_data.csv

  build_features:
    cmd: python src/features/build_features.py
    deps:
      - src/features/build_features.py
      - data/processed/cleaned_data.csv
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/
